# Generated by Django 4.2.1 on 2023-06-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
                ('question_category', models.CharField(choices=[('technology', 'Technology'), ('science', 'Science'), ('arts & literature', 'Arts & Literature'), ('health & medicine', 'Health & Medicine'), ('business & finance', 'Business & Finance'), ('travel & tourism', 'Travel & Tourism'), ('education', 'Education'), ('sports & fitness', 'Sports & Fitness'), ('food & cooking', 'Food & Cooking'), ('entertainment', 'Entertainment'), ('history', 'History'), ('relationships & dating', 'Relationships & Dating'), ('politics & government', 'Politics & Government'), ('environment & sustainability', 'Environment & Sustainability'), ('religion & spirituality', 'Religion & Spirituality'), ('personal development & self-improvement', 'Personal Development & Self-Improvement')], max_length=250, verbose_name='категория')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления вопроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['question_text'],
            },
        ),
    ]
