# Generated by Django 4.2.1 on 2023-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('Технология', 'Technology'), ('Наука', 'Science'), ('Исскусство и Литература', 'Arts & Literature'), ('Здоровье и Медицина', 'Health & Medicine'), ('Бизнесс и Финанс', 'Business & Finance'), ('Путешествие и Туризм', 'Travel & Tourism'), ('Образование', 'Education'), ('Спорт и Фитнес', 'Sports & Fitness'), ('Еда и Готовка', 'Food & Cooking'), ('Развлечение', 'Entertainment'), ('История', 'History'), ('Отношения и Знакомства', 'Relationships & Dating'), ('Политики и Правительство', 'Politics & Government'), ('Окружающая среда и Устойчивость', 'Environment & Sustainability'), ('Религия и Духовность', 'Religion & Spirituality'), ('Личностное развитие и Саморазвитие', 'Personal Development & Self-Improvement')], max_length=250, verbose_name='категория'),
        ),
    ]
