# Generated by Django 4.2.1 on 2023-06-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0002_alter_question_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('Технология', 'Технология'), ('Наука', 'Наука'), ('Исскусство и Литература', 'Исскусство и Литература'), ('Здоровье и Медицина', 'Здоровье и Медицина'), ('Бизнесс и Финанс', 'Бизнесс и Финанс'), ('Путешествие и Туризм', 'Путешествие и Туризм'), ('Образование', 'Education'), ('Спорт и Фитнес', 'Sports & Fitness'), ('Еда и Готовка', 'Food & Cooking'), ('Развлечение', 'Entertainment'), ('История', 'History'), ('Отношения и Знакомства', 'Relationships & Dating'), ('Политики и Правительство', 'Politics & Government'), ('Окружающая среда и Устойчивость', 'Environment & Sustainability'), ('Религия и Духовность', 'Religion & Spirituality'), ('Личностное развитие и Саморазвитие', 'Personal Development & Self-Improvement')], max_length=250, verbose_name='категория'),
        ),
    ]
