# Generated by Django 4.2.1 on 2023-06-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('image_answer', models.ImageField(blank=True, upload_to='media/images/', verbose_name='Фото ответ')),
                ('video_answer', models.FileField(blank=True, upload_to='media/videos/', verbose_name='Видео ответ')),
                ('audio_answer', models.FileField(blank=True, upload_to='media/audio/', verbose_name='Аудио')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления ответа')),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_app.question', verbose_name='Текст вопроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['user'],
            },
        ),
    ]
