# Generated by Django 4.2.1 on 2023-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='video_answer',
            field=models.URLField(blank=True, max_length=250, verbose_name='Видео ответ'),
        ),
    ]
