# Generated by Django 4.2.1 on 2023-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers_app', '0002_alter_answer_video_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audio_answer',
            field=models.BooleanField(default=False, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image_answer',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Фото ответ'),
        ),
    ]
