# Generated by Django 4.2.1 on 2023-06-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers_app', '0003_alter_answer_audio_answer_alter_answer_image_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='audio_answer',
            new_name='permission',
        ),
    ]
